send_learned_ir_command:
  target:
    entity:
      domain: remote
      integration: tuya_local
  fields:
    command:
      required: true
      example: "Play"
      selector:
        object:
    device:
      example: "TV"
      selector:
        text:
    emitter_entity_id:
      example: "infrared.my_ir_emitter"
      required: true
      selector:
        entity:
          filter:
            domain: infrared

list_cloud_devices:
  fields:
    device_id:
      example: "bfa8c98xxxxxxxxxxxxxxx"
      selector:
        text:

refresh_local_keys:
  fields:
    dry_run:
      default: false
      selector:
        boolean:
